### ISSUE TITLE
Error: CPI error 'Bosh::Clouds::CloudError' with message 'can't use multiple availability zones: nova, GLT' in 'create_vm' CPI method

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry-incubator/bosh-openstack-cpi-release#124]
hello,

i've 2 AZ  on my cloud-config: TZF & GLT 

all works like i charm and i deploy cf-deployment without pain.
But today , i've a new message on my concourse :

`Error: CPI error 'Bosh::Clouds::CloudError' with message 'can't use multiple availability zones: nova, GLT' in 'create_vm' CPI method`

i use cf-deployment 1.19~1.20
and  bosh 264.7.0

on my cloud-config :

```
azs:
- name: z1
  cloud_properties:
    availability_zone: GLT
- name: z2
  cloud_properties:
    availability_zone: TZF
- name: z3
  cloud_properties:
    availability_zone: TZF
```

(i do 2 azs with same availability zone for have 3 azs, as some release needs 3 azs)

do you know why i have this nova AZ ?  i don't refer this anywhere ...
it's a default name for defaut az ? 

thanks for yours support
