### ISSUE TITLE
Human readable VM names not working with full BOSH deployment

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-incubator/bosh-openstack-cpi-release#26]
Opening issue as requested at http://cf-bosh.70367.x6.nabble.com/cf-bosh-Announcement-OpenStack-CPI-release-v23-td1356.html.

My bosh-init VM and the BOSH VM itself do have human readable names, but the systems created by BOSH do not.  Please see the email thread above for my theory as to why but it looks like the full BOSH director configurtion did not get populated with the necessary properties to enable human readable VMs.  Here is a snippet of the bosh.yml used to deploy full BOSH from a bosh-init system (just showing the relevant properties are present):

```yaml
---
name: bosh
director_uuid: 43a6f3ad-3063-434a-ada8-802f48e487ad

release:
  name: bosh
  version: 255.3

properties:
  registry:
    endpoint: http://user:pass@10.10.10.10:25777
    
  openstack:
    human_readable_vm_names: true
```
