### ISSUE TITLE
Cannot start instance in cloud with multiple hypervisors

### ISSUE THREAD

**Issue by mauromorales** [cloudfoundry-incubator/bosh-openstack-cpi-release#39]
Hello, I was trying to install bosh and cf but came up with the following issue:

The cloud where it is running can run docker, kvm and vmware instances. After uploading the stemcell with bosh/bosh-init the image would try to run on docker which of course ended up failing. It was until the hypervisor type property was set that it was possible to instanciate it.

`glance image-update --property hypervisor_type="kvm"`

Since this information is given by the stemcell would it be possible to add the property via the CPI after the image get's uploaded?

Thanks!

**Comment by cppforlife** [comment]
@mauromorales looks like CPI properly picks it up (https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb#L116) but stemcell doesnt include it:

```
$ tar -Oxvf ~/Downloads/bosh-stemcell-3232.11-openstack-kvm-ubuntu-trusty-go_agent.tgz stemcell.MF
x stemcell.MF---
name: bosh-openstack-kvm-ubuntu-trusty-go_agent
version: '3232.11'
bosh_protocol: 1
sha1: 6f7c4f90482771a63f570ea0e5f8579e45229f10
operating_system: ubuntu-trusty
cloud_properties:
  name: bosh-openstack-kvm-ubuntu-trusty-go_agent
  version: '3232.11'
  infrastructure: openstack
  hypervisor: kvm
  disk: 3072
  disk_format: qcow2
  container_format: bare
  os_type: linux
  os_distro: ubuntu
  architecture: x86_64
  auto_disk_config: true
```

I'm not too sure what's going to happen to different environments when hypervisor type is specified. Do you happen to know if this matters in envs with only one hypervisor? Wdyt @loewenstein?

**Comment by loewenstein** [comment]
@cppforlife have you seen the "hypervisor" property in the stemcell? My current assumption (as stated in tracker as well) is a simple typo in the cpi code. Can you rule that out?

**Comment by mauromorales** [comment]
Here are the contents of `stemcell.MF`:

```
---                                                                                                                                                                                           
name: bosh-openstack-kvm-ubuntu-trusty-go_agent                                                                                                                                               
version: '3232.8'                                                                                                                                                                             
bosh_protocol: 1                                                                                                                                                                              
sha1: 46825c4d7f89778b358affea80271f9cdbba0570                                                                                                                                                
operating_system: ubuntu-trusty                                                                                                                                                               
cloud_properties:                                                                                                                                                                             
  name: bosh-openstack-kvm-ubuntu-trusty-go_agent                                                                                                                                             
  version: '3232.8'                                                                                                                                                                           
  infrastructure: openstack                                                                                                                                                                   
  hypervisor: kvm                                                                                                                                                                             
  disk: 3072                                                                                                                                                                                  
  disk_format: qcow2                                                                                                                                                                          
  container_format: bare                                                                                                                                                                      
  os_type: linux                                                                                                                                                                              
  os_distro: ubuntu                                                                                                                                                                           
  architecture: x86_64                                                                                                                                                                        
  auto_disk_config: true 
```

And hypervisor seems to be rejected by https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/fb8e99d6e10674d5374d1b447c94dfe60435d83c/src/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb#L118

The rest of the attributes seem to work fine
